/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author PC
 */
public class FrameBibliotecario extends javax.swing.JFrame {

    /**
     * Creates new form FrameBibliotecario
     */
    public FrameBibliotecario() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCrearUsuario = new javax.swing.JButton();
        jButtonIngresarLibro = new javax.swing.JButton();
        jButtonIngresarTesis = new javax.swing.JButton();
        jButtonBuscarEstudiante = new javax.swing.JButton();
        jButtonBuscarDocente = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(420, 350));
        setMinimumSize(new java.awt.Dimension(420, 350));
        setPreferredSize(new java.awt.Dimension(420, 350));
        getContentPane().setLayout(null);

        jButtonCrearUsuario.setBackground(new java.awt.Color(0, 102, 102));
        jButtonCrearUsuario.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jButtonCrearUsuario.setText("Crear Usuario");
        jButtonCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCrearUsuario);
        jButtonCrearUsuario.setBounds(10, 120, 120, 23);

        jButtonIngresarLibro.setBackground(new java.awt.Color(0, 102, 102));
        jButtonIngresarLibro.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jButtonIngresarLibro.setText("Ingresar Libro");
        jButtonIngresarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarLibroActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIngresarLibro);
        jButtonIngresarLibro.setBounds(140, 120, 120, 23);

        jButtonIngresarTesis.setBackground(new java.awt.Color(0, 102, 102));
        jButtonIngresarTesis.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jButtonIngresarTesis.setText("Ingresar Tesis");
        jButtonIngresarTesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarTesisActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIngresarTesis);
        jButtonIngresarTesis.setBounds(270, 120, 120, 23);

        jButtonBuscarEstudiante.setBackground(new java.awt.Color(0, 102, 102));
        jButtonBuscarEstudiante.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jButtonBuscarEstudiante.setText("Buscar Estudiante");
        jButtonBuscarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarEstudianteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscarEstudiante);
        jButtonBuscarEstudiante.setBounds(40, 200, 140, 23);

        jButtonBuscarDocente.setBackground(new java.awt.Color(0, 102, 102));
        jButtonBuscarDocente.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jButtonBuscarDocente.setText("Buscar Docente");
        jButtonBuscarDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarDocenteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscarDocente);
        jButtonBuscarDocente.setBounds(210, 200, 123, 23);

        jLabel4.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 51, 0));
        jLabel4.setText("SISTEMA BIBLIOTECARIO");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 40, 310, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Docent.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCrearUsuarioActionPerformed

    private void jButtonIngresarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonIngresarLibroActionPerformed

    private void jButtonIngresarTesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarTesisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonIngresarTesisActionPerformed

    private void jButtonBuscarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarEstudianteActionPerformed
        // TODO add your handling code here:
        FrameEstudiante ventanaEstudiante = new FrameEstudiante();
        ventanaEstudiante.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBuscarEstudianteActionPerformed

    private void jButtonBuscarDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarDocenteActionPerformed
        // TODO add your handling code here:
       FrameDocente ventanaDocente = new FrameDocente();
        ventanaDocente.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBuscarDocenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameBibliotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameBibliotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameBibliotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameBibliotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameBibliotecario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarDocente;
    private javax.swing.JButton jButtonBuscarEstudiante;
    private javax.swing.JButton jButtonCrearUsuario;
    private javax.swing.JButton jButtonIngresarLibro;
    private javax.swing.JButton jButtonIngresarTesis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
