/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtUserName = new javax.swing.JTextField();
        txtPaswordConfir = new javax.swing.JPasswordField();
        txtPasword = new javax.swing.JPasswordField();
        txtUserLastN = new javax.swing.JTextField();
        txtUseerUser = new javax.swing.JTextField();
        btRegister = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUserName.setFont(new java.awt.Font("Comic Sans MS", 2, 16)); // NOI18N
        txtUserName.setText("Enter Name");
        txtUserName.setBorder(null);
        jPanel1.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 170, 260, 30));

        txtPaswordConfir.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        txtPaswordConfir.setText("jPasswordField1");
        txtPaswordConfir.setBorder(null);
        jPanel1.add(txtPaswordConfir, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 483, 260, 30));

        txtPasword.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        txtPasword.setText("jPasswordField1");
        txtPasword.setBorder(null);
        jPanel1.add(txtPasword, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 404, 260, 30));

        txtUserLastN.setFont(new java.awt.Font("Comic Sans MS", 2, 16)); // NOI18N
        txtUserLastN.setText("Enter Last Name");
        txtUserLastN.setBorder(null);
        jPanel1.add(txtUserLastN, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 248, 260, 30));

        txtUseerUser.setFont(new java.awt.Font("Comic Sans MS", 2, 16)); // NOI18N
        txtUseerUser.setText("Enter Username");
        txtUseerUser.setBorder(null);
        jPanel1.add(txtUseerUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 326, 260, 30));

        btRegister.setBackground(new java.awt.Color(94, 33, 41));
        btRegister.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        btRegister.setForeground(new java.awt.Color(255, 255, 255));
        btRegister.setBorder(null);
        btRegister.setBorderPainted(false);
        btRegister.setContentAreaFilled(false);
        btRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 540, 230, 34));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/B_R.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 660));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 660));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPasswordField txtPasword;
    public javax.swing.JPasswordField txtPaswordConfir;
    public javax.swing.JTextField txtUseerUser;
    public javax.swing.JTextField txtUserLastN;
    public javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
