/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author quizh
 */
public class UsuarioSeleccion extends javax.swing.JFrame {

    /**
     * Creates new form UsuarioSeleccion
     */
    public UsuarioSeleccion() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonDocente = new javax.swing.JButton();
        jButtonEstudiante = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButtonRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 320));
        setMinimumSize(new java.awt.Dimension(400, 320));
        setPreferredSize(new java.awt.Dimension(400, 320));
        getContentPane().setLayout(null);

        jButtonDocente.setBackground(new java.awt.Color(255, 255, 255));
        jButtonDocente.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonDocente.setText("DOCENTE");
        jButtonDocente.setToolTipText("");
        jButtonDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDocenteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDocente);
        jButtonDocente.setBounds(50, 160, 110, 30);

        jButtonEstudiante.setBackground(new java.awt.Color(255, 255, 255));
        jButtonEstudiante.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonEstudiante.setText("ESTUDIANTE");
        jButtonEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEstudianteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEstudiante);
        jButtonEstudiante.setBounds(210, 160, 130, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SISTEMA BIBLIOTECARIO");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 80, 290, 50);

        jButtonRegresar.setBackground(new java.awt.Color(204, 255, 255));
        jButtonRegresar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonRegresar.setText("REGRESAR");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresar);
        jButtonRegresar.setBounds(260, 240, 110, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/seleccionusuario.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-260, 0, 690, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEstudianteActionPerformed
        // TODO add your handling code here:
        LoginEstudiante ventanaEstudiante = new LoginEstudiante();
        ventanaEstudiante.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonEstudianteActionPerformed

    private void jButtonDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDocenteActionPerformed
        // TODO add your handling code here:
        LoginDocente ventanaDocente = new LoginDocente();
        ventanaDocente.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonDocenteActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        // TODO add your handling code here:
        FrameInicio ventanaInicio = new FrameInicio();
        ventanaInicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuarioSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuarioSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuarioSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuarioSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsuarioSeleccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDocente;
    private javax.swing.JButton jButtonEstudiante;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
